#!/usr/bin/env python3
"""
vendor.py - fetch the viewer's third-party assets into static/.

  python tools/vendor.py            # download everything that is missing
  python tools/vendor.py --force    # re-download even if present

Why vendor at all: the recording PC sits on a LAN and is often reached over
Tailscale with no route to the public internet. A viewer that pulls hls.js from
a CDN loses live playback on Android exactly when you need it. Fonts are the
same story, one notch less severe (they degrade to system faces).

Run this once; the files land in static/ and are served by guard.py. It is a
build step, never called at runtime, so guard.py itself stays dependency-free.

Licences of what this pulls:
  hls.js      Apache-2.0   (Dailymotion)
  IBM Plex    OFL-1.1      (IBM)
"""

import re
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STATIC = REPO / "static"

HLS_VERSION = "1.5.13"
HLS_URL = f"https://cdnjs.cloudflare.com/ajax/libs/hls.js/{HLS_VERSION}/hls.min.js"

# Only the families/weights index.html actually uses.
GOOGLE_CSS = ("https://fonts.googleapis.com/css2"
              "?family=IBM+Plex+Mono:wght@400;500;600"
              "&family=IBM+Plex+Sans:wght@400;500;600&display=swap")
# A modern UA is required or Google serves ttf instead of the much smaller woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

FACE_RE = re.compile(
    r"/\*\s*(?P<subset>[\w\[\]-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}", re.S)


def fetch(url: str, binary=True):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def get_hls(force: bool) -> None:
    out = STATIC / "hls.min.js"
    if out.is_file() and not force:
        print(f"  skip  {out.name} (already there)")
        return
    data = fetch(HLS_URL)
    # Sanity-check the payload before writing: a CDN error page would otherwise
    # be saved as "hls.min.js" and the failure would surface much later, as a
    # blank live tab on someone's phone.
    if not (200_000 < len(data) < 2_000_000 and b"Hls" in data
            and b"MEDIA_ATTACHED" in data):
        sys.exit(f"downloaded {len(data)} bytes that do not look like hls.js "
                 "- refusing to write it")
    out.write_bytes(data)
    print(f"  ok    {out.name}  {len(data)/1024:.0f} KB  (v{HLS_VERSION})")


def get_fonts(force: bool) -> list:
    """Grab the latin subset only, then write the matching @font-face CSS.

    The UI text is Korean, and IBM Plex has no Hangul - Korean already falls
    back to the system face. Pulling every subset would multiply the size for
    glyphs this viewer never draws.

    Google serves some families as ONE variable file shared by every weight
    (IBM Plex Sans today) and others as one file per weight (IBM Plex Mono).
    So faces are grouped by URL: same URL means one download and a single
    @font-face covering the whole weight range.
    """
    css = fetch(GOOGLE_CSS, binary=False)
    groups = {}
    for m in FACE_RE.finditer(css):
        if m.group("subset") != "latin":
            continue
        body = m.group("body")
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = int(re.search(r"font-weight:\s*(\d+)", body).group(1))
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        groups.setdefault((family, url), []).append(weight)

    faces = []
    for (family, url), weights in groups.items():
        slug = family.lower().replace(" ", "-")
        lo, hi = min(weights), max(weights)
        name = f"{slug}-{'var' if lo != hi else lo}.woff2"
        out = STATIC / name
        if out.is_file() and not force:
            print(f"  skip  {name} (already there)")
        else:
            data = fetch(url)
            out.write_bytes(data)
            print(f"  ok    {name}  {len(data)/1024:.0f} KB  "
                  f"weight {lo}" + (f"-{hi} (variable)" if lo != hi else ""))
        faces.append((family, lo, hi, name))
    write_font_css(faces)
    return faces


def write_font_css(faces) -> None:
    """index.html links this instead of carrying the rules inline.

    Generated, never hand-edited: the weights and filenames have to track
    whatever Google actually served, and a hand-kept copy would drift.
    """
    lines = ["/* generated by tools/vendor.py - do not edit */"]
    for family, lo, hi, name in sorted(faces, key=lambda f: (f[0], f[1])):
        lines += [
            "@font-face{",
            f"  font-family:'{family}';",
            "  font-style:normal;",
            f"  font-weight:{lo if lo == hi else f'{lo} {hi}'};",
            "  font-display:swap;",
            f"  src:url('/static/{name}') format('woff2');",
            "}",
        ]
    (STATIC / "fonts.css").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  ok    fonts.css  {len(faces)} face(s)")


def main():
    force = "--force" in sys.argv
    STATIC.mkdir(exist_ok=True)
    print(f"vendoring into {STATIC}")
    get_hls(force)
    faces = get_fonts(force)
    if not faces:
        sys.exit("no latin @font-face blocks parsed - Google changed the CSS shape")
    total = sum(f.stat().st_size for f in STATIC.iterdir() if f.is_file())
    print(f"done. static/ is {total/1024:.0f} KB over "
          f"{len(list(STATIC.iterdir()))} files")


if __name__ == "__main__":
    main()
